import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import Kickoff from "@/components/Kickoff";
import Nav from "@/components/Nav";
import Showcase from "@/components/Showcase";
import Head from "next/head";

function Home() {
  return (
    <>
      <Head>
        <title>H. E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Hero />
      <Showcase />
      <Kickoff />
      <Footer />
    </>
  );
}

export default Home;
